spring.application.name=WeatherMonitoringSystem

#Run with docker - compose
spring.datasource.url=jdbc:mysql://mysqldb:3306/weather_monitoring

#Run it locally ( Recommended)
#spring.datasource.url=jdbc:mysql://localhost:3306/weather_monitoring


spring.datasource.username=admin
spring.datasource.password=admin
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# OpenWeatherMap API Configuration
openweathermap.api.key=
openweathermap.api.url=https://api.openweathermap.org/data/2.5/weather

# Alterting thresholds
# Weather condition to trigger an alert
weather.alert.mainCondition=Clear
weather.alert.consecutive.updates=2
tempThreshold=35

# Email configuration
# Change this to your SMTP server
spring.mail.host=smtp.gmail.com
spring.mail.port=587

# Your email address
#spring.mail.username=kulkarnivivek1992@gmail.com
#spring.mail.password=vvjj vice anqq kagk
#spring.mail.properties.mail.smtp.auth=true
#spring.mail.properties.mail.smtp.starttls.enable=true




